/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Alert: typeof import('./components/ui/Alert.vue')['default']
    AppBarMenu: typeof import('./components/header/tools/AppBarMenu.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LeftDrawer: typeof import('./components/sidebar/LeftDrawer.vue')['default']
    Navbar: typeof import('./components/header/Navbar.vue')['default']
    Navbr: typeof import('./components/header/Navbr.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Snackbar: typeof import('./components/ui/Snackbar.vue')['default']
    UserMenu: typeof import('./components/header/tools/UserMenu.vue')['default']
  }
}
